apache/tez

- tez-examples/src/main/java/org/apache/tez/examples/HashJoinExample.java
- tez-examples/src/main/java/org/apache/tez/examples/JoinDataGen.java
- tez-examples/src/main/java/org/apache/tez/examples/SortMergeJoinExample.java
- tez-tests/src/main/java/org/apache/tez/mapreduce/examples/FilterLinesByWord.java
- tez-tests/src/main/java/org/apache/tez/mapreduce/examples/TestOrderedWordCount.java
- tez-tests/src/main/java/org/apache/tez/mapreduce/examples/UnionExample.java
- tez-tests/src/test/java/org/apache/tez/test/TestTezJobs.java
FileSystem other than the default FileSystem.
> TEZ-4086. Allow various examples to work when outputPath is on a FileSystem other than the default FileSystem.

- tez-api/src/main/java/org/apache/tez/common/counters/TaskCounter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/api/TezRuntimeConfiguration.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/ShuffleUtils.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleInputEventHandlerImpl.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleManager.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/writers/BaseUnorderedPartitionedKVWriter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/writers/UnorderedPartitionedKVWriter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/output/UnorderedKVOutput.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/output/UnorderedPartitionedKVOutput.java
- tez-runtime-library/src/main/proto/ShufflePayloads.proto
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/common/writers/TestUnorderedPartitionedKVWriter.java
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/conf/TestUnorderedPartitionedKVOutputConfig.java
- tez-tests/src/test/java/org/apache/tez/test/TestTezJobs.java
PR request based on https://issues.apache.org/jira/browse/TEZ-4075?focusedCommentId=16944252&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16944252
This enables data transfer over wire. In subsequent jira, in memory caching can be enabled for IFile. Details are provided in the link posted earlier.
> TEZ-4075: Reimplement tez.runtime.transfer.data-via-events.enabled

- .asf.yaml
According to hive example:
https://github.com/apache/hive/blob/master/.asf.yaml
documentation:
https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
current defaults:
https://gitbox.apache.org/schemes.cgi?tez
> TEZ-4278: Show PR link in Jira

- tez-dag/src/main/java/org/apache/tez/dag/app/rm/node/AMNodeImpl.java
I'm happy to file a JIRA if necessary; I wasn't sure if that was useful or not for a 1-character change. :) 
The log message looks like this currently: 
```
2020-02-10 20:12:58,267 [INFO] [Dispatcher thread {Central}] |node.AMNodeImpl|: Attempt failedon node: ...
```
> fix typo: missing space

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/TezRuntimeUtils.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/utils/CodecUtils.java
Issue: [TEZ-4302](https://issues.apache.org/jira/browse/TEZ-4302) NullPointerException in CodecUtils when bufferSizeProp is null
> TEZ-4302: NullPointerException in CodecUtils when bufferSizeProp is null

- tez-common/src/main/java/org/apache/tez/common/StreamHelper.java
- tez-dag/src/main/java/org/apache/tez/dag/history/logging/impl/SimpleHistoryLoggingService.java
- tez-plugins/tez-protobuf-history-plugin/src/main/java/org/apache/tez/dag/history/logging/proto/ProtoMessageWriter.java
Following exception is thrown whenever we do ProtoMessageWriter.hflush on S3, which internally calls S3ABlockOutputStream.hflush which is not supported and it throws java.lang.UnsupportedOperationException. 
bdffe22d96ae [mdc@18060 class="yarn.YarnUncaughtExceptionHandler" level="ERROR" thread="HistoryEventHandlingThread"] Thread Thread[HistoryEventHandlingThread, 5,main] threw an Exception.^Mjava.lang.UnsupportedOperationException: S3A streams are not Syncable^M at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.hflush(S3ABlockOutputStream.java:657)^M at org.apache.hadoop.fs.FS DataOutputStream.hflush(FSDataOutputStream.java:136)^M at org.apache.hadoop.io.SequenceFile$Writer.hflush(SequenceFile.java:1367)^M at org.apache.tez.dag.history.logging.proto.ProtoMessageWriter.hflush(ProtoMessageWr …
> TEZ-4305: Invoke hflush, only if the stream supports it

- tez-plugins/tez-history-parser/src/main/java/org/apache/tez/history/parser/ProtoHistoryParser.java
- tez-plugins/tez-history-parser/src/main/java/org/apache/tez/history/parser/SimpleHistoryParser.java
- tez-plugins/tez-history-parser/src/main/java/org/apache/tez/history/parser/datamodel/BaseInfo.java
- tez-plugins/tez-history-parser/src/main/java/org/apache/tez/history/parser/utils/Utils.java
- tez-plugins/tez-protobuf-history-plugin/src/main/java/org/apache/tez/dag/history/logging/proto/HistoryEventProtoJsonConversion.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/Analyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/AnalyzerDriver.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/ContainerReuseAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/CriticalPathAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/DagOverviewAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/HungTaskAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/InputReadErrorAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/LocalityAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/OneOnOneEdgeAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/ShuffleTimeAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/SkewAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/SlowNodeAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/SlowTaskIdentifier.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/SlowestVertexAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/SpillAnalyzerImpl.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/TaskAttemptResultStatisticsAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/TaskConcurrencyAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/TaskHangAnalyzer.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/TezAnalyzerBase.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/VertexLevelCriticalPathAnalyzer.java
**Problems fixed:**
1. DagInfo.getEvents() returns an array with only 1 element
2. All of the events (DagInfo.getEvents(), VertexInfo,getEvents()) have "0" as timestamp
3. HistoryEventProtoJsonConversion: TASK_FINISHED event and VERTEX_FINISHED events don't contain starTime, only timeTaken, so as timeTaken is fix, startTime should be derivated from that, not the opposite way (this caused non-sense task durations in analyzers while parsing proto history files)
4. Fix an NPE in TaskAttemptResultStatisticsAnalyzer
5. float truncation problem in SkewAnalyzer
6. counters format workaround for TEZ-4324
**Refactoring:**
removed configuration object from analyzers as TezAnalyzerBase is already a Configured class
**New analyzers:**
InputReadErrorAnalyzer
DagOverviewAnalyzer
TaskHangAnalyzer …
> TEZ-4231: SimpleHistoryParser doesn't merge events correctly

- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/BroadcastEdgeManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/OneToOneEdgeManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/OneToOneEdgeManagerOnDemand.java
- tez-dag/src/test/java/org/apache/tez/dag/app/TestMockDAGAppMaster.java
Singleton Collections are by their design immutable. There is no need to wrap them in an unmodifiableCollection.
> TEZ-4321: Do Not Wrap Singleton Collections

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/InputAttemptFetchFailure.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/FetcherOrderedGrouped.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java
PR contains 2 changes:
1. adds original cause to InputAttemptFetchFailure
2. reporting hostFailures to AM
original exception in hive client was:
```
Caused by: java.io.IOException: Map_2: Shuffle failed with too many fetch failures and insufficient progress!failureCounts=45, pendingInputs=5947, fetcherHealthy=false, reducerProgressedEnough=false, reducerStalled=false
at org.apache.tez.runtime.library.common.shuffle.orderedgrouped.ShuffleScheduler.isShuffleHealthy(ShuffleScheduler.java:1060)
at org.apache.tez.runtime.library.common.shuffle.orderedgrouped.ShuffleScheduler.copyFailed(ShuffleScheduler.java:798)
at org.apache.tez.runtime.library.common.shuffle.orderedgrouped.FetcherOrderedGrouped.setupConnection(FetcherOrderedGrouped.java:391)
at …
```
> TEZ-4336: ShuffleScheduler should try to report the original exception (when shuffle becomes unhealthy)

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-api/src/main/java/org/apache/tez/runtime/api/events/InputReadErrorEvent.java
- tez-api/src/main/java/org/apache/tez/serviceplugins/api/ContainerLauncherContext.java
- tez-api/src/main/proto/Events.proto
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/Vertex.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/event/TaskAttemptEventOutputFailed.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/Edge.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/TaskAttemptImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/node/AMNodeImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/node/AMNodeTracker.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/node/PerSourceNodeTracker.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestTaskAttempt.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/api/impl/TezEvent.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/api/TezRuntimeConfiguration.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/Fetcher.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/FetcherErrorTestingConfig.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/FetcherWithInjectableErrors.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleManager.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/FetcherOrderedGrouped.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/FetcherOrderedGroupedWithInjectableErrors.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java
The fix is actually to store downstreamBlamingHosts on vertex level. This is a map which simply stores a set of downstream hosts that reported fetch failure for every upstream host. The idea is to detect the upstream node failure better, and I'm trying to achieve this by assuming if downstream tasks from at least n nodes (n is configurable) reported failures for an upstream host, then the upstream tasks will be marked as OUTPUT_LOST and will rerun. As we're handling this on vertex level, we can fail a mapper task even if we get the first fetch failure reported blaming that, as we already figured out the mapper host itself has been reported as a possible root cause of failures.
Changes in this patch:
1. propagating host of the downstream task through tez event
2. handling hosts in the …
> TEZ-4338: Tez should consider node information to realize OUTPUT_LOST as early as possible - upstream(mapper) problems

- tez-api/src/main/java/org/apache/tez/common/CachedEntity.java
- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientImpl.java
- tez-api/src/test/java/org/apache/tez/dag/api/client/rpc/TestDAGClient.java
TEZ-4349 DAGClient gets stuck with invalid cached DAGStatu
The `cachedDagStatus` should be valid for a certain amount of time, or certain number of retires.
When the `cachedDAGStatus` expires, the DAGClient tries to pull from AM or the RM.
An error in fetching the status from both AM and RM, would return null to the caller.
- The expiration time can be configured using `TezConfiguration.TEZ_CLIENT_DAG_STATUS_CACHE_TIMEOUT_MINUTES` `tez.client.dag.status.cache.timeout-minutes`, and the default is 5. The `timeUnit` of the expiration is minutes.
- Added a new UT `TestDAGClient.testGetDagStatusWithCachedStatusExpiration`
- ran the following unit tests: `mvn test -Dtest=TestDAGClient,TestTezClient,TestMockDAGAppMaster`
> TEZ-4349. DAGClient gets stuck with invalid cached DAGStatus

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-common/src/main/java/org/apache/tez/common/DagContainerLauncher.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/TaskImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/ContainerLauncherManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/ContainerLauncherWrapper.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/DeletionTracker.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/DeletionTrackerImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/LocalContainerLauncher.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/TaskAttemptFailedDeleteRunnable.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/TezContainerLauncherImpl.java
- tez-dag/src/test/java/org/apache/tez/dag/app/launcher/TestContainerLauncherWrapper.java
- tez-plugins/tez-aux-services/src/main/java/org/apache/tez/auxservices/ShuffleHandler.java
- tez-plugins/tez-aux-services/src/test/java/org/apache/tez/auxservices/TestShuffleHandler.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/TezRuntimeUtils.java
Delete intermediate attempt data for failed task attempts for Tez Shuffle Handler
> TEZ-4129: Delete intermediate attempt data for failed attempts for Shuffle Handler

- tez-tests/src/test/java/org/apache/tez/test/TestSecureShuffle.java
I've changed the recommended `TEZ_AM_TASK_MAX_FAILED_ATTEMPTS` configuration value and made some test run to see the run times. The default value for maximum failed attempts per task was 4 so I did 4 different run for each test where I reduced the config value by 1 in each run.
`[sslInCluster:true, resultWithTezSSL:0, resultWithoutTezSSL:1, asyncHttp:false, taskMaxFailed:4]`	**1min 25sec**
`[sslInCluster:true, resultWithTezSSL:0, resultWithoutTezSSL:1, asyncHttp:false, taskMaxFailed:3]`	**1min 0sec**
`[sslInCluster:true, resultWithTezSSL:0, resultWithoutTezSSL:1, asyncHttp:false, taskMaxFailed:2]`	**48sec 655ms**
`[sslInCluster:true, resultWithTezSSL:0, resultWithoutTezSSL:1, asyncHttp:false, taskMaxFailed:1]`	**53sec 320ms**
`[sslInCluster:true, resultWithTezSSL:0, resultWithoutTezSSL:1, …
> TEZ-4381: Speed up TestSecureShuffle

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-common/src/main/java/org/apache/tez/common/DagContainerLauncher.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/event/VertexEventType.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/event/VertexShuffleDataDeletion.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/DAGImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexShuffleDataDeletionContext.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/ContainerLauncherManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/ContainerLauncherWrapper.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/DeletionTracker.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/DeletionTrackerImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/LocalContainerLauncher.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/TezContainerLauncherImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/VertexDeleteRunnable.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestVertexImpl.java
- tez-dag/src/test/java/org/apache/tez/dag/app/launcher/TestContainerLauncherWrapper.java
- tez-plugins/tez-aux-services/src/main/java/org/apache/tez/auxservices/ShuffleHandler.java
- tez-plugins/tez-aux-services/src/test/java/org/apache/tez/auxservices/TestShuffleHandler.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/TezRuntimeUtils.java
For applications like pig where processing times can be very long, applications may choose to delete intermediate data for a sub dag. For example if a DAG has synced data to HDFS, all upstream intermediate data can be safely deleted.
> TEZ-3363: Delete intermediate data at the vertex level for Shuffle Handler

- tez-mapreduce/src/main/java/org/apache/hadoop/mapred/split/TezGroupedSplitsInputFormat.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/grouper/TezSplitGrouper.java
Tez input splits can be opened asynchronously. This will reduce the amount of time spent for s3 to prepare the connection and opening the object
> TEZ-4397 Open Tez Input splits asynchronously

- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/DagDeleteRunnable.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/TaskAttemptFailedDeleteRunnable.java
- tez-dag/src/main/java/org/apache/tez/dag/app/launcher/VertexDeleteRunnable.java
- tez-plugins/tez-aux-services/pom.xml
Shuffle handler fails with ClassNotFound org.apache.tez.shaded.javax.net.ssl.SSLHandshakeException
when SSL is enabled. Excluding shading of javax.net.** from
tez-aux-services uber jar.
DagDeleteTracker is hardcoded to generate URL with http. Fixing it to
use https when SSL config is enabled.
> TEZ-4399: ShuffleHandler fails with SSLHandshakeException not found when SSL is enabled

- tez-api/src/main/java/org/apache/tez/client/TezClient.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/rpc/DAGClientAMProtocolBlockingPBServerImpl.java
Use Path.getFilesystem api to get the correct FileSystem object for given staging path
To prevent Wrong FS issue when the staging directory and warehouse root are on different storage locations and tez-conf size exceeds the IPC limit.
No.
Manual tests.
> TEZ-4406: Use Path.getFilesystem api to get the correct FileSystem object for given staging path

- tez-ui/src/main/resources/META-INF/LICENSE.txt
- tez-ui/src/main/webapp/bower-shrinkwrap.json
- tez-ui/src/main/webapp/bower.json
- tez-ui/src/main/webapp/ember-cli-build.js
Update FileSaver dependency to latest bower supported dependency
Previous dependency files were no longer available
No.
Manual tests.
> TEZ-4411: Update FileSaver dependency

- pom.xml
Currently we are on slf4j 1.7.30,  As per https://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.30 , There are four CVE's against this version.
1. CVE-2022-23305
2. CVE-2022-23302
3. CVE-2021-4104
4. CVE-2019-17571
Upgrading to 1.7.36 https://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.36 should solve the security concerns.
Reference
1. https://github.com/apache/tez/blob/master/pom.xml#L256
2. https://github.com/apache/tez/blob/master/pom.xml#L240
> TEZ-4403: Upgrade SLF4J Version To 1.7.36

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClient.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientImpl.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientInternal.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientTimelineImpl.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/rpc/DAGClientRPCImpl.java
- tez-api/src/main/proto/DAGClientAMProtocol.proto
- tez-common/src/main/java/org/apache/tez/common/web/AbstractServletToControllerAdapter.java
- tez-common/src/main/java/org/apache/tez/common/web/ServletToControllerAdapters.java
- tez-common/src/main/java/org/apache/tez/common/web/package-info.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/DAGClientHandler.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/rpc/DAGClientAMProtocolBlockingPBServerImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/web/WebUIService.java
- tez-mapreduce/src/main/java/org/apache/tez/dag/api/client/MRDAGClient.java
- tez-tests/src/test/java/org/apache/tez/test/TestAM.java
Add some diagnostic endpoints to TezAM's WebUIService
- add new endpoints to webuiservice
- make port range configurable
- publish the web endpoint through dag client
- unit test included: TestAM
- checked in browser too
> TEZ-4347: Add some diagnostic endpoints to TezAM's WebUIService

- tez-api/src/main/java/org/apache/tez/common/TezCommonUtils.java
- tez-api/src/test/java/org/apache/tez/common/TestTezCommonUtils.java
TEZ-4412 ensure mkDirForAM create directory with special permissions
I found TezClientUtils has method ensureStagingDirExists.It will check whether the path "stagingArea" exists, if it exists, check the permission, if not, call the function "TezCommonUtils.mkDirForAM" to create.But in method mkDirForAM,it use mkdir(path, permission) to create, if umask too strict such as 777,this directory will set with 000 permission.So we need to ensure the directory has right permission.
In this patch, I compared the permissions of the files with the expected permissions. If they are inconsistent, then log this and use setPermission to grant directory permissions.
> TEZ-4412 ensure mkDirForAM create directory with special permissions

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
[TEZ-4423][CVE-2021-44906] Upgrade minimist version from 0.0.8 to 1.2.6 to fix the vulnerability.
Link to JIRA : https://issues.apache.org/jira/browse/TEZ-4423
> TEZ-4423[CVE-2021-44906] Upgrade minimist version from 0.0.8 to 1.2.6

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
[TEZ-4424] [CVE-2021-3918] Upgrade json-schema from 0.2.3 to 0.4.0 to fix the vulnerability. 
Link to JIRA : https://issues.apache.org/jira/browse/TEZ-4424
> TEZ-4424: [CVE-2021-3918] Upgrade json-schema from 0.2.3 to 0.4.0

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
[WS-2020-0345] Upgrade jsonpointer version from 4.0.1 to 4.1.0 to fix the vulnerability.
Link to JIRA : https://issues.apache.org/jira/browse/TEZ-4425
> TEZ-4425: [WS-2020-0345] Upgrade jsonpointer version from 4.0.1 to 4.1.0

- tez-ui/pom.xml
- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
[TEZ-4426][CVE-2018-1000620] Upgrade cryptiles from 2.0.5 to 4.1.2 to fix the vulnerability.
Link to JIRA : https://issues.apache.org/jira/browse/TEZ-4426
> [TEZ-4426][CVE-2018-1000620] Upgrade cryptiles from 2.0.5 to 4.1.2

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
[TEZ-4427][CVE-2019-10744] Upgrade lodash.merge version to 4.6.2 to fix the vulnerability.
Link to JIRA : https://issues.apache.org/jira/browse/TEZ-4427
> [TEZ-4427][CVE-2019-10744] Upgrade lodash.merge version to 4.6.2

- tez-api/src/main/java/org/apache/tez/client/TezClientUtils.java
- tez-api/src/test/java/org/apache/tez/client/TestTezClientUtils.java
Refer https://issues.apache.org/jira/browse/TEZ-4430 for details on this fix.
> TEZ-4430: Fix tez.task.launch.cmd-opts property not working

- docs/src/site/markdown/install.md
[TEZ-4439] Update the protobuf documentation in TEZ codebase. 
Link to the issue : https://issues.apache.org/jira/browse/TEZ-4439
The protobuf dependency was upgraded from 2.5.0 to 3.19.4 as tracked in this issue : https://issues.apache.org/jira/browse/TEZ-4363. But there were certain mentions of protobuf 2.5.0 in the documentations of protobuf within the TEZ codebase. Raised this PR to update those documentations.
> [TEZ-4439] Update the protobuf documentation in TEZ codebase

- pom.xml
- tez-plugins/tez-protobuf-history-plugin/src/main/java/org/apache/tez/dag/history/logging/proto/DagManifesFileScanner.java
- tez-plugins/tez-protobuf-history-plugin/src/main/java/org/apache/tez/dag/history/logging/proto/HistoryEventProtoConverter.java
https://issues.apache.org/jira/browse/TEZ-4435
> TEZ-4435: use jackson v2 - jackson v1 is EOL and full of security issues

- tez-dag/src/main/java/org/apache/tez/dag/app/rm/DagAwareYarnTaskScheduler.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/YarnTaskSchedulerService.java
https://issues.apache.org/jira/browse/TEZ-4440
> TEZ-4440. When tez app run in yarn fed cluster, may throw NPE

- pom.xml
JIRA: [TEZ-4449](https://issues.apache.org/jira/projects/TEZ/issues/TEZ-4449?filter=allissues): Upgrade jettison to 1.5.1 to fix CVE-2022-40149.
> TEZ-4449: Upgrade jettison to 1.5.1 to fix CVE-2022-40149.

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleInputEventHandlerImpl.java
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/TestShuffleInputEventHandlerImpl.java
- tez-runtime-library/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixed failure in fetching shuffle data when it's transferred via CompositeRoutedDataMovementEvent. 
Added unit test to test the failure scenario.
Jira ticket: https://issues.apache.org/jira/browse/TEZ-4450
> TEZ-4450: Shuffle data fetch fails when shuffle data is transferred via CompositeRoutedDataMovementEvent

- tez-api/src/test/java/org/apache/tez/common/TestTezCommonUtils.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexImpl.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/MergeManager.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/TezMerger.java
- tez-tests/src/test/java/org/apache/tez/test/TestInput.java
- tez-tests/src/test/java/org/apache/tez/test/TestOutput.java
JIRA: [TEZ-4454: remove extra commas.](https://issues.apache.org/jira/browse/TEZ-4454)
While reading the code, I found that there are extra commas in the code, I searched the whole project and removed the extra commas.
> TEZ-4454: remove extra semicolons

- tez-plugins/tez-aux-services/src/main/java/org/apache/tez/auxservices/ShuffleHandler.java
**What changes were proposed in this pull request?**
Adding LoggingHandler in ShuffleHandler pipeline for better debuggability.
**Why are the changes needed?**
For corner case debugging, it will be helpful to understand when netty processed OPEN/BOUND/CLOSE/RECEIVED/CONNECTED events along with payload details.
Adding "LoggingHandler" in ChannelPipeline mode to help in debugging.
**Does this PR introduce any user-facing change?**
No.
**How was this patch tested?**
Pre-commit testing.
> TEZ-4455: Add LoggingHandler in ShuffleHandler pipeline for better debuggability

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
TEZ-4456: Upgraded is-my-json-valid version to 2.20.3 to fix the vulnerability. This is a critical vulnerability to fix. The parent JIRA can be tracked under : https://issues.apache.org/jira/browse/TEZ-4419
> TEZ-4456: Upgraded is-my-json-valid version to 2.20.3 to fix the vulnerability

- tez-mapreduce/src/main/java/org/apache/hadoop/mapred/split/TezGroupedSplitsInputFormat.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/grouper/TezSplitGrouper.java
Tez input splits can be opened asynchronously. This will reduce the amount of time spent for s3 to prepare the connection and opening the object.
The changes are taken from the original PR: https://github.com/apache/tez/pull/195 with some additional changes
1. Disable the feature by default (to avoid regression in dependent engines)
2. Minor refactoring
> TEZ-4397: Open Tez Input splits asynchronously

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/test/java/org/apache/tez/dag/app/TestDAGAppMaster.java
When Tez DAG recovery is failed because of some reason in the second retry of any Tez AM, then in corner case scenario, Tez Job sets DAG state to IDLE
Once the DAG state is set to IDLE, then after checkAndHandleSessionTimeout(), Tez AM will try to shutdown the DAG, and since recovery was failed so there will not be any running DAGs
If there are no RUNNING DAGs and state of DAG is IDLE, then by default AM sets the status to SUCCEEDED
This can result in issues in dependent systems like Hive which will move ahead with other tasks in pipeline assuming the DAG was success, this can result in moving empty data in Hive
As part of this PR, we are proposing to introduce a patch in TEZ, which introduces a config, which when set, then in case of recovery missing in attempts > 1, it fails the DAG …
> TEZ-4474: Added config to fail the DAG status when recovery data is missing

- tez-plugins/tez-aux-services/src/main/java/org/apache/tez/auxservices/ShuffleHandler.java
- tez-plugins/tez-aux-services/src/test/java/org/apache/tez/auxservices/TestShuffleHandler.java
1. Fixed issues in ShuffleHandler
actual fixes are "EMPTY_LAST_CONTENT" and "ch.writeAndFlush"
2. Refactored TestShuffleHandler and introduced a new test case that calls the ShuffleHandler thoroughly
tested with a couple of queries on TPCDS 100GB (which had frequent timeouts before the patch)
> TEZ-4460: Read timed out in shuffle handler - incorrect usage of EMPTY_LAST_CONTENT and channel write

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java
This patch resolved a deadlock between different parts of ShuffleSheduler:
1. https://github.com/apache/tez/blob/6bd6f9cdcf47176ab78fb5aea555583af50cc2d3/tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java#L1062
2. https://github.com/apache/tez/blob/6bd6f9cdcf47176ab78fb5aea555583af50cc2d3/tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java#L1336
The patch
a) removed synchronized keyword from copyFailed method, but let parts of that method remain sync
b) removed the boolean return mess from methods that called from copyFailed and introduced a clearer IOException pattern and let the exceptionReporter be called from a non-sync part, at one single place
> TEZ-4334: Fix deadlock in ShuffleScheduler between ShuffleScheduler.close() and the ShufflePenaltyReferee thread

- pom.xml
[TEZ-4485](https://issues.apache.org/jira/browse/TEZ-4485)
> TEZ-4485:  Upgrade jettison to 1.5.4 due to CVE-2023-1436

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
JIRA link : https://issues.apache.org/jira/browse/TEZ-4484. This address critical vulnerability CVE-2022-24999
> TEZ-4484 : [CVE-2022-24999] Upgrade qs from 6.2.3 to 6.2.4 to fix the vulnerability.

- tez-ui/src/main/webapp/package.json
- tez-ui/src/main/webapp/yarn.lock
JIRA link : https://issues.apache.org/jira/browse/TEZ-4483. This PR addresses critical vulnerabilities [CVE-2017-20165, CVE-2017-20165]
> TEZ-4483 : [CVE-2017-20165, CVE-2017-20165] Upgrade debug to 2.6.9 to fix the vulnerability

- tez-ui/src/main/webapp/.bowerrc
This approach updates `Bowerrc` to use `bower.herokuapp` mirror to avoid Bower Registry `CERT_EXPIRE `issue
> TEZ-4492 : Approach 1 : Update Bower Registry to a different mirror

- pom.xml
- tez-api/pom.xml
- tez-mapreduce/pom.xml
- tez-runtime-library/pom.xml
As described in jira, mvn site command fails for some modules. Instead of taking care of javadoc compliance of some non-production modules, it would make sense disable the plugin for all of the modules for which javadocs are not published,
> TEZ-4495: mvnsite fails for some modules - No public or protected classes found to document

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/TezThreadDumpHelper.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TezChild.java
- tez-tests/src/test/java/org/apache/tez/test/TestTezJobs.java
> TEZ-4344: Collect jstack periodically from all containers.

- tez-api/src/main/java/org/apache/tez/common/counters/DAGCounter.java
- tez-api/src/main/java/org/apache/tez/serviceplugins/api/TaskScheduler.java
- tez-api/src/main/java/org/apache/tez/serviceplugins/api/TaskSchedulerContext.java
- tez-dag/src/main/java/org/apache/tez/dag/app/ContainerLauncherContextImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/DAG.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/DAGImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/DagAwareYarnTaskScheduler.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/LocalTaskSchedulerService.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/TaskSchedulerContextImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/TaskSchedulerContextImplWrapper.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/TaskSchedulerManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/YarnTaskSchedulerService.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestDAGImpl.java
- tez-dag/src/test/java/org/apache/tez/dag/app/launcher/TestContainerLauncherManager.java
- tez-dag/src/test/java/org/apache/tez/dag/app/rm/TestContainerReuse.java
- tez-dag/src/test/java/org/apache/tez/dag/app/rm/TestTaskSchedulerHelpers.java
- tez-dag/src/test/java/org/apache/tez/dag/app/rm/TestTaskSchedulerManager.java
- tez-ext-service-tests/src/test/java/org/apache/tez/dag/app/rm/TezTestServiceTaskSchedulerService.java
- tez-ext-service-tests/src/test/java/org/apache/tez/dag/app/rm/TezTestServiceTaskSchedulerServiceWithErrors.java
All the changes are according to the conversation on Jira + addressing comments on this PR so far.
Added comments myself to clarify what unrelated changes mean
> TEZ-2119: Counter for launched containers

- pom.xml
[Details for Why?](https://devhub.checkmarx.com/cve-details/Cx78f40514-81ff/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea)
> TEZ-4517: Upgrade commons-collection4 to 4.4.

- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TezTaskRunner2.java
- tez-runtime-internals/src/test/java/org/apache/tez/runtime/task/TestTaskExecution2.java
Tested on Hive.
**Without Patch**
```
----------------------------------------------------------------------------------------------
VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED  
----------------------------------------------------------------------------------------------
Map 1            container       RUNNING      1          0        0        1       4       0  
Reducer 2        container        INITED      1          0        0        1       0       0  
----------------------------------------------------------------------------------------------
VERTICES: 00/02  [>>--------------------------] 0%    ELAPSED TIME: 16.68 s    
----------------------------------------------------------------------------------------------
```
**With Patch**
``` …
```
> TEZ-4110: Make Tez fail fast when DFS quota is exceeded.

- tez-runtime-library/src/main/java/org/apache/tez/dag/library/vertexmanager/ShuffleVertexManagerBase.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/ExternalSorter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/PipelinedSorter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/dflt/DefaultSorter.java
- tez-runtime-library/src/test/java/org/apache/tez/dag/library/vertexmanager/TestShuffleVertexManagerUtils.java
Currently, we need to configure the compressed size for ordered outputs and the decompressed size for unordered output. It makes sense if we can have consistent semantics.
https://issues.apache.org/jira/browse/TEZ-4521
> TEZ-4521: Partition stats should be always uncompressed size

- docs/src/site/markdown/talks.md
The links under Presentations and Talks on Tez section for User meetup recrodings is broken.
Link for recording: https://hortonworks.webex.com/hortonworks/ldr.php?AT=pb&SP=MC&rID=125516477&rKey=d147a3c924b64496
as well as meetup group link: http://www.meetup.com/Apache-Tez-User-Group/events/130852782/ doesn't exist anymore.
> TEZ-4525: Remove broken links from site

- tez-dist/pom.xml
Tez was unable to utilize Maven's multi-threaded compilation due to dependency issues, resulting in slow compilation. However, this problem was resolved through module dependency resolution. After implementing parallel compilation with Maven, the compilation speed increased several times over.
> TEZ-4520: Enable Parallel Compilation for TEZ

- tez-common/src/main/java/org/apache/tez/util/LoggingUtils.java
Remove the trace from WARN log & put it only in DEBUG mode
> TEZ-4039: Addendum: Tez should inject dag id, query id into MDC.

- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/grouper/TezSplitGrouper.java
TEZ-4526: Avoid calling LocationProvider#getPreferredLocations multiple times while generating grouped splits
> TEZ-4526: Avoid calling LocationProvider#getPreferredLocations multiple times while generating grouped splits

- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TaskRunner2Callable.java
Put IOStatistics in TaskRunner
> TEZ-4451: ThreadLevel IO Stats Support for TEZ.

- tez-api/src/main/java/org/apache/tez/common/RPCUtil.java
- tez-api/src/main/java/org/apache/tez/dag/api/NoCurrentDAGException.java
- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientImpl.java
- tez-api/src/test/java/org/apache/tez/dag/api/client/rpc/TestDAGClient.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/DAGClientHandler.java
- tez-dag/src/test/java/org/apache/tez/dag/api/client/TestDAGClientHandler.java
This is an AM + client-side change to make DagClient realize much faster when its asking for the status of a DAG which is not present.
> TEZ-4543: Throw a special exception to DagClient when there is no current DAG

- tez-api/src/main/java/org/apache/tez/runtime/api/InputInitializerContext.java
- tez-api/src/main/java/org/apache/tez/runtime/api/events/InputDataInformationEvent.java
- tez-api/src/main/proto/Events.proto
- tez-api/src/test/java/org/apache/tez/runtime/api/events/TestCompositeDataMovementEvent.java
- tez-api/src/test/java/org/apache/tez/runtime/api/events/TestInputDataInformationEvent.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/RootInputInitializerManager.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/TezRootInputInitializerContextImpl.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/hadoop/MRInputHelpers.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/input/MRInput.java
- tez-mapreduce/src/test/java/org/apache/tez/mapreduce/TezTestUtils.java
- tez-mapreduce/src/test/java/org/apache/tez/mapreduce/hadoop/TestMRInputHelpers.java
- tez-runtime-internals/src/main/java/org/apache/tez/common/ProtoConverters.java
This patch implements the tez side of the scenario described in HIVE-28165 + TEZ-4548.
tez-api changes: 
- extend InputDataInformationEvent with serialized path
- test coverage for API methods
tez-runtime-internals:
- adjust proto converters to the new field
tez-mapreduce changes:
- MRInput to handle serialized path if found in the event
- basic test coverage for the implementation methods in MRInputHelpers
testing: tested on cluster (together with HIVE-28165), solved an OOM issue, also tez unit tests added
> TEZ-4548: InputDataInformationEvent to be read from serialized payload from filesystem

- tez-dag/src/main/java/org/apache/tez/client/LocalClient.java
This PR is about to make LocalClient fail fast if it cannot create the folders instead of going on and failing later in a confusing way. See Jira for details.
> TEZ-4555: Fail fast in LocalClient if the dirs (log, local) haven't been created

- pom.xml
JIRA: [TEZ-4551](https://issues.apache.org/jira/browse/TEZ-4551). Upgrade commons-io to 2.16.0.
We are currently using commons-io version 2.8.0, which is an older version (Sep 09, 2020). Commons-io has been upgraded to 2.16.0 (Mar 28, 2024). We can try to upgrade the version to 2.16.0.
> TEZ-4551. Upgrade commons-io to 2.16.0.

- pom.xml
- tez-api/pom.xml
- tez-tests/pom.xml
JIRA: TEZ-4560. Upgrade bouncycastle to 1.77 due to CVE.
There are 2 CVE issues in bcprov-jdk15on, CVE-2023-33202 and CVE-2023-33201. We can find more information at the following link:
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on/1.70
The link to the CVE is as follows: 
[CVE-2023-33202](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-33202)
[CVE-2023-33201](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-33201)
We can upgrade bcprov-jdk15on to bcprov-jdk18on to address the CVE issues.
> TEZ-4560. Upgrade bouncycastle to 1.77 due to CVE.

- pom.xml
JIRA: [TEZ-4552. Upgrade protobuf to 3.24.4 due to CVE.](https://issues.apache.org/jira/browse/TEZ-4552)
I found that there are 3 CVE issues that we need to deal with. These CVE issues are related to protobuf. Our protobuf uses 3.21.1, which is an old version. This PR will try to upgrade the protobuf version to solve the CVE issue.
- [CVE-2022-3171](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3171)
- [CVE-2022-3509](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3509)
- [CVE-2022-3510](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3510)
> TEZ-4552. Upgrade protobuf to 3.24.4 due to CVE.

- tez-api/src/main/java/org/apache/tez/dag/api/client/DAGClientImpl.java
- tez-api/src/test/java/org/apache/tez/dag/api/client/rpc/TestDAGClient.java
Some unit tests were broken by [TEZ-4543](https://issues.apache.org/jira/browse/TEZ-4543), where we simply returned a failed DAG if the requested DAG status cannot be found. This completely breaks recovery scenarios where the dagClient might keep asking for the failed DAGs status (while the AM restarts after a failure).
Considering recovery works, the client should simply consider if recovery is enabled and behave accordingly. This patch reverts the behavior in case of recovery to pre-TEZ-4543, but if there is no recovery, TEZ-4543 is a fair assumption and still makes the client able to return much faster in case of the specialized exception implying that the DAG is already lost.
Unit tests have been run manually with this patch: TestDAGRecovery, TestAMRecovery, TestRecovery
> TEZ-4559: Fix Retry logic in case of Recovery

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/PipelinedSorter.java
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/common/sort/impl/TestPipelinedSorter.java
See [TEZ-4542](https://issues.apache.org/jira/browse/TEZ-4542) for details.
> TEZ-4542: Tez application may fail due to int overflow when record size is large and sort memory is low.

- tez-api/src/main/java/org/apache/tez/client/FrameworkClient.java
- tez-api/src/main/java/org/apache/tez/client/TezClient.java
- tez-api/src/main/java/org/apache/tez/client/TezYarnClient.java
- tez-api/src/test/java/org/apache/tez/client/TestTezClient.java
- tez-dag/src/main/java/org/apache/tez/client/LocalClient.java
This PR exposes Tez AM host and port from TezClient (and the underlying FrameworkClient).
> TEZ-4564: TezClient to expose Tez AM host:port

- tez-common/src/main/java/org/apache/tez/common/web/ProfileServlet.java
This PR is for fixing the same problems as mentioned and tested in [HIVE-28305](https://issues.apache.org/jira/browse/HIVE-28305)
please look at that PR for details:
https://github.com/apache/hive/pull/5281
> TEZ-4568: ProfileServlet: add html to output formats and prepare for profiler 3.0

- tez-plugins/tez-protobuf-history-plugin/src/main/java/org/apache/tez/dag/history/logging/proto/ProtoMessageWritable.java
- tez-plugins/tez-protobuf-history-plugin/src/test/java/org/apache/tez/dag/history/logging/proto/TestProtoHistoryLoggingService.java
Refer to this: [HIVE-28026](https://issues.apache.org/jira/browse/HIVE-28026) and https://github.com/apache/hive/pull/5033
> TEZ-4540: Reading proto data more than 2GB from multiple splits fails

- tez-api/src/main/java/org/apache/tez/common/counters/DAGCounter.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/DAG.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/DAGImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/TaskSchedulerManager.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestDAGImpl.java
- tez-dag/src/test/java/org/apache/tez/dag/app/rm/TestTaskSchedulerManager.java
tested on a small tez container mode cluster
with 2 healthy and running yarn nodemanagers:
```
INFO  : org.apache.tez.common.counters.DAGCounter:
...
INFO  :    NODE_USED_COUNT: 2
INFO  :    NODE_TOTAL_COUNT: 2
```
after stopping 1 nodemanager:
```
INFO  : org.apache.tez.common.counters.DAGCounter:
...
INFO  :    NODE_USED_COUNT: 1
INFO  :    NODE_TOTAL_COUNT: 2
```
after decommissioning 1 nodemanager:
```
INFO  : org.apache.tez.common.counters.DAGCounter:
...
INFO  :    NODE_USED_COUNT: 1
INFO  :    NODE_TOTAL_COUNT: 1
```
also tested with LLAP on Cloudera CDW (3 LLAP daemons)
```
INFO  :    NODE_USED_COUNT: 3
INFO  :    NODE_TOTAL_COUNT: 3
```
> TEZ-4554: Counter for used nodes within a DAG

- pom.xml
Please refer to [TEZ-4557](https://issues.apache.org/jira/browse/TEZ-4557), for error stacktrace.
> TEZ-4557: Revert TEZ-4303, NoClassDefFoundError because of missing httpclient jar

- tez-api/src/main/java/org/apache/tez/runtime/api/OutputCommitterContext.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/OutputCommitterContextImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexImpl.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/committer/MROutputCommitter.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/common/Utils.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/hadoop/MRJobConfig.java
- tez-mapreduce/src/main/java/org/apache/tez/mapreduce/output/MROutput.java
- tez-mapreduce/src/test/java/org/apache/tez/mapreduce/output/TestMROutput.java
Some committers require a job-wide UUID to function correctly. Adding the AM JobID to the JobConf
will allow applications to pass that to
the committers that need it.
> TEZ-4547: Add Tez AM JobID to the JobConf

- pom.xml
JIRA: TEZ-4550. Upgrade commons-cli to 1.6.0.
> TEZ-4550. Upgrade commons-cli to 1.6.0.

- tez-tools/tez-javadoc-tools/src/main/java/org/apache/tez/tools/javadoc/util/XmlWriter.java
- tez-tools/tez-javadoc-tools/src/main/resources/apache-licence.xml.header
tested:
built tez-javadoc-tools procject
```
cd tez-runtime-library
mvn site
```
checked ./target/site/apidocs/configs/tez-runtime-default-template.xml
> TEZ-3322: Add Apache license to the generated tez-configuration-template files

- pom.xml
There are CVE's in roaringbit 0.7.45:
https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap/0.7.45
As there is a plan in hive as well to upgrade roaringbit to 1.2.x hence better to keep them in sync.
> TEZ-4578: Upgrade roaringbit version to 1.2.1 to fix CVE's

- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/TaskImpl.java
When some conditions skip speculative execution, NUM_SPECULATIONS should not be counted.
> TEZ-4585: Fix counters for speculation.

- pom.xml
Upgrade jersey to 1.19.4
[TEZ-4586](https://issues.apache.org/jira/browse/TEZ-4586)
Hadoop and Hive have already upgraded jersey version to 1.19.4, so tez should upgrade jersey version to 1.19.4 too.
None, that I am aware of.
CI
> TEZ-4586: Upgrade jersey to 1.19.4

- docs/src/site/markdown/releases/apache-tez-0-10-2.md
- docs/src/site/markdown/releases/apache-tez-0-10-3.md
- docs/src/site/markdown/releases/apache-tez-0-10-4.md
- docs/src/site/markdown/releases/index.md
- docs/src/site/site.xml
- pom.xml
work done:
- upgraded maven site plugin
- upgraded fluido skin to be compatible with the site plugin
- created missing release pages markdown
- removed deprecated releases from the menu (still available in the all releases page)
testing:
- ran:
```
cd docs
mvn clean site
```
opened the webpage: docs/target/index.html
> TEZ-4587: Synchronize Tez site with the current markup

- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestTaskAttempt.java
Fixing the typo in the test file TestTaskAttempt
> TEZ-4591: Fix typo on TestTaskAttempt: expectedEvenstAfterTerminating

- tez-api/src/main/java/org/apache/tez/common/counters/DAGCounter.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/event/DAGEventCounterUpdate.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/TaskAttemptImpl.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestTaskAttempt.java
tested on cluster with different scenarios, hive LLAP
1. 2 queries running in parallel, leading to task kills, also I killed random nodes during the test
```
INFO  : Run DAG                               149.16s
INFO  :    NUM_FAILED_TASKS: 18
INFO  :    NUM_KILLED_TASKS: 11078
INFO  :    NUM_SUCCEEDED_TASKS: 774
INFO  :    TOTAL_LAUNCHED_TASKS: 11870
INFO  :    DURATION_FAILED_TASKS_MILLIS: 125559
INFO  :    DURATION_KILLED_TASKS_MILLIS: 2474797
INFO  :    DURATION_SUCCEEDED_TASKS_MILLIS: 15740900
ratio of failed to succeeded durations: 0.0080 = 0.80%
ratio of killed to succeeded durations: 0.1575 = 15.75%
```
low killed/succeeded ratio implies the hive LLAP behavior (task preempted quite fast, 11078 task kills didn't contributed that much)
2. single query, but more aggressive node …
> TEZ-4589: Counter for the overall duration of succeeded/failed/killed task attempts

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/PipelinedSorter.java
After [TEZ-4542](https://issues.apache.org/jira/browse/TEZ-4542), app may run into an issue of real small sortspan (per record in this case), eventually the job failed due to timeout.
Here, fix int overflow problem in another way.
> TEZ-4577: SortSpan could be created real small, resulting in eventual job failure

- tez-api/src/main/java/org/apache/tez/common/counters/FileSystemCounter.java
- tez-runtime-internals/pom.xml
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/metrics/FileSystemStatisticUpdater.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/metrics/TaskCounterUpdater.java
- tez-runtime-internals/src/test/java/org/apache/tez/runtime/metrics/TestFileSystemStatisticUpdater.java
- tez-runtime-internals/src/test/java/org/apache/tez/runtime/metrics/TestTaskCounterUpdater.java
- tez-runtime-internals/src/test/java/org/apache/tez/runtime/task/TestTaskExecution2.java
This a rebased, reworked version of the last patch on TEZ-3331:
https://issues.apache.org/jira/secure/attachment/12926702/TEZ-3331.8.patch
> TEZ-3331: Add operation specific HDFS counters for Tez UI

- pom.xml
[Build](https://github.com/apache/tez/actions/runs/12312373636/job/34364280062#step:4:11762) tries to download release artifacts from snapshots repo:
```
Downloading from apache.snapshots.https: https://repository.apache.org/content/repositories/snapshots/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom (2.7 kB at 392 kB/s)
```
This change disables releases for `apache.snapshots.https`.
https://issues.apache.org/jira/browse/TEZ-4593
```
$ mvn -N --batch-mode eu.maveniverse.maven.plugins:toolbox:list-repositories
...
[INFO] --- toolbox:0.6.0:list-repositories (default-cli) …
```
> TEZ-4593. Disable releases for apache.snapshots.https repo

- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-common/src/main/java/org/apache/tez/runtime/hook/TezDAGHook.java
- tez-common/src/main/java/org/apache/tez/runtime/hook/TezTaskAttemptHook.java
- tez-common/src/main/java/org/apache/tez/runtime/hook/package-info.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/ThreadDumpDAGHook.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/TezThreadDumpHelper.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TezChild.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/ThreadDumpTaskAttemptHook.java
- tez-tests/src/test/java/org/apache/tez/test/TestTezJobs.java
https://issues.apache.org/jira/browse/TEZ-4527
> TEZ-4527: Add generic and pluggable hooks for DAGs and task attempts

- pom.xml
- tez-ext-service-tests/pom.xml
JIRA: [TEZ-4549](https://issues.apache.org/jira/projects/TEZ/issues/TEZ-4549?). Upgrade Hadoop Version to 3.4.0.
hadoop has been upgraded to 3.4.0, try to upgrade hadoop to 3.4.0.
Local compilation successful.
```
[INFO] tez ................................................ SUCCESS [  2.206 s]
[INFO] hadoop-shim ........................................ SUCCESS [ 27.433 s]
[INFO] tez-api ............................................ SUCCESS [ 36.299 s]
[INFO] tez-build-tools .................................... SUCCESS [  0.233 s]
[INFO] tez-common ......................................... SUCCESS [  2.093 s]
[INFO] tez-runtime-internals .............................. SUCCESS [  8.123 s]
[INFO] tez-runtime-library ................................ SUCCESS [ 16.348 s]
[INFO] tez-mapreduce …
```
> TEZ-4549: Upgrade Hadoop Version to 3.4.1.

- tez-common/src/main/java/org/apache/tez/common/AsyncDispatcher.java
- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/DAGImpl.java
- tez-dag/src/main/java/org/apache/tez/dag/app/rm/YarnTaskSchedulerService.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/ContainerReporter.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/Fetcher.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/FetcherOrderedGrouped.java
Fix t1 < t2 kind of comparisons
> TEZ-4537: Fix several time comparison issues.

- tez-dag/src/main/java/org/apache/tez/dag/app/dag/impl/VertexImpl.java
- tez-tests/src/test/java/org/apache/tez/test/TestAMRecoveryAggregationBroadcast.java
Let an AM correctly restore its state and restart tasks.
https://issues.apache.org/jira/browse/TEZ-4569
> TEZ-4569: SCATTER_GATHER + BROADCAST hangs on DAG Recovery

- pom.xml
- tez-api/pom.xml
https://issues.apache.org/jira/browse/TEZ-4319
Implicit dependency on snappy-java-1.0.5 was added by TEZ-4113. It causes error on platforms like aarch64 for which snappy binary is not provided.
Adding explicit dependency on recent snappy-java supporting aarch64 and ppc64le should address the issue.
> TEZ-4319. Add explicit dependency on snappy-java to tez-api.

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/CompositeInputAttemptIdentifier.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/InputAttemptIdentifier.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleInputEventHandlerImpl.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/ShuffleManager.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/orderedgrouped/ShuffleScheduler.java
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/common/TestInputIdentifiers.java
https://issues.apache.org/jira/browse/TEZ-4061
> TEZ-4061: InputAttemptIdentifier and CompositeInputAttemptIdentifier cannot be compared for equality

- pom.xml
JIra - [TEZ-4599](https://issues.apache.org/jira/browse/TEZ-4599)
After Upgarding netty to 4.1.116.Final, netty libraries package image looks like the below
> TEZ-4599: Bump netty to 4.1.116.Final

- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TezChild.java
As described in [TEZ-4605](https://issues.apache.org/jira/browse/TEZ-4605)
I modified `tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java` and `tez-runtime-internals/src/main/java/org/apache/tez/runtime/task/TezChild.java`
I want to enable org.apache.hadoop.ipc.CallerContext when running TEZ on yarn, so that we can trace how the application interacted with hdfs files.
I modified the code and build the whole project, then I test on my own hadoop cluster, we can see the callcontext information in hdfs-audit.log.
here is a screenshot of it:
> TEZ-4605: Enbale hadoop CallerContext in TezChild and DAGAppMaster

- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/sort/impl/PipelinedSorter.java
The ByteBuffer.mark() method returns ByteBuffer itself in Java 8, but starting with JDK 9+, it returns a more specific subclass (like HeapByteBuffer or DirectByteBuffer), which is incompatible with method signatures expecting ByteBuffer.
When running the same code in JDK 17, this mismatch triggers a NoSuchMethodError due to binary incompatibility.
> TEZ-4609: JDK-17: Fix ByteBuffer mark incompatibility in PipelinedSorter.

- tez-dag/src/main/resources/tez-container-log4j.properties
Please check [TEZ-4608](https://issues.apache.org/jira/browse/TEZ-4608), for more information
> TEZ-4608: Remove appender EventCounter from tez-container-log4j.properties

- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-plugins/tez-history-parser/src/main/java/org/apache/tez/history/ATSImportTool.java
- tez-tests/src/main/java/org/apache/tez/mapreduce/examples/helpers/SplitsInClientOptionParser.java
- tez-tools/analyzers/job-analyzer/src/main/java/org/apache/tez/analyzer/plugins/TezAnalyzerBase.java
TEZ-4626: Remove usage of deprecated classes of commons-cli
> TEZ-4626: Remove usage of deprecated classes of commons-cli

- BUILDING.txt
- Jenkinsfile
- build-tools/docker/Dockerfile
- build-tools/test-patch.sh
- pom.xml
- tez-api/pom.xml
- tez-api/src/main/java/org/apache/tez/client/TezClientUtils.java
- tez-dag/pom.xml
- tez-runtime-internals/pom.xml
- tez-runtime-library/findbugs-exclude.xml
TEZ-4624: Replace findbugs plugin with spotbugs
> TEZ-4624: Replace findbugs plugin with spotbugs

- .github/workflows/build.yml
- BUILDING.txt
- Jenkinsfile
- build-tools/docker/Dockerfile
- pom.xml
- tez-api/src/main/java/org/apache/tez/client/TezClientUtils.java
- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-api/src/test/java/org/apache/tez/client/TestTezClientUtils.java
- tez-dag/pom.xml
- tez-ext-service-tests/pom.xml
- tez-ext-service-tests/src/test/java/org/apache/tez/dag/app/rm/TezTestServiceTaskSchedulerService.java
- tez-runtime-library/src/main/java/org/apache/tez/runtime/library/common/shuffle/impl/SimpleFetchedInputAllocator.java
- tez-runtime-library/src/test/java/org/apache/tez/runtime/library/common/shuffle/impl/TestSimpleFetchedInputAllocator.java
- tez-tests/pom.xml
TEZ-4598: JDK-17: Migrate Tez to jdk17 (compile & runtime)
> TEZ-4598: JDK-17: Migrate Tez to jdk17 (compile & runtime)

- .github/workflows/build.yml
- Jenkinsfile
- build-tools/docker/Dockerfile
- pom.xml
**Example Job with Tez-JDK-21 & Hadoop-3.4.1**
> TEZ-4636: Move to JDK-21+

- tez-tools/analyzers/job-analyzer/src/test/java/org/apache/tez/analyzer/TestAnalyzer.java
Occasionally,  attempt comes back as 000001_2 and doesn't match
> TEZ-4565. TestAnalyzer subtest testInternalPreemption is flaky

- tez-api/findbugs-exclude.xml
- tez-api/pom.xml
- tez-api/src/main/java/org/apache/tez/client/registry/AMRecord.java
- tez-api/src/main/java/org/apache/tez/client/registry/package-info.java
- tez-api/src/main/java/org/apache/tez/dag/api/TezConfiguration.java
- tez-api/src/main/java/org/apache/tez/dag/api/TezConstants.java
- tez-dag/src/main/java/org/apache/tez/client/LocalClient.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/registry/AMRegistry.java
- tez-dag/src/main/java/org/apache/tez/dag/api/client/registry/package-info.java
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/LocalDAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/utils/AMRegistryUtils.java
- tez-dag/src/test/java/org/apache/tez/dag/api/client/registry/TestAMRegistry.java
- tez-dag/src/test/java/org/apache/tez/dag/app/MockDAGAppMaster.java
- tez-dag/src/test/java/org/apache/tez/dag/app/TestDAGAppMaster.java
As described on jira:
Interface and reflective plugin configuration for a pool of AMs identified by a namespace.
The registry should allow each DAGClientServer to register/unregister themselves from a pool.
Basically, this PR introduces AMRegistry that is going to be implemented in [TEZ-4007](https://issues.apache.org/jira/browse/TEZ-4007) by a Zookeeper AM registry.
> TEZ-4008: Pluggable AM FrameworkServices and AmExtensions (2/3)

- tez-dag/findbugs-exclude.xml
- tez-dag/src/main/java/org/apache/tez/dag/app/DAGAppMaster.java
- tez-dag/src/main/java/org/apache/tez/dag/app/PluginManager.java
- tez-dag/src/test/java/org/apache/tez/dag/app/TestDAGAppMaster.java
- tez-dag/src/test/java/org/apache/tez/dag/app/dag/impl/TestVertexImpl2.java
- tez-dag/src/test/java/org/apache/tez/dag/app/rm/TestTaskSchedulerManager.java
From Jira:
The proposal is to create a PluginManager to offload much of the plugin management code from the already overloaded DAGAppMaster class (including its static methods).
This issue was discovered while working on TEZ-4007, which only exacerbated the situation with the addition of AMExtensions (not AMExtensions themselves, but rather the original code in DAGAppMaster). Let’s clean this up first before proceeding with TEZ-4007.
Testing done with affected unit tests
`
mvn install -Dtest=TestTaskSchedulerManager,TestVertexImpl2,TestDAGAppMaster -pl ./tez-dag
`
> TEZ-4647: Refactor plugin management from DAGAppMaster

- tez-tools/tez-tfile-parser/src/main/java/org/apache/tez/tools/TFileLoader.java
- tez-tools/tez-tfile-parser/src/main/java/org/apache/tez/tools/TFileRecordReader.java
Ran the command: 
```
mvn clean install -DskipTests -pl '!tez-ui' -Ptools
```
> TEZ-4651: Fix compilation in tez-tools module because of spotless
